/**
 * Markdown Reporter — 가독성 높은 접근성 검사 리포트 생성
 */

import type { FullReport, ScreenResult, ClassifiedIssue } from '@shared/types';

export class MarkdownReporter {
  /**
   * Markdown 리포트 문자열 생성
   */
  generate(report: FullReport): string {
    const lines: string[] = [];

    lines.push(this.header(report));
    lines.push(this.summarySection(report));
    lines.push(this.topViolationsSection(report));

    for (const screen of report.screens) {
      lines.push(this.screenSection(screen));
    }

    lines.push(this.footer(report));

    return lines.join('\n\n');
  }

  private header(report: FullReport): string {
    const { metadata } = report;
    return [
      `# ♿ Accessibility Report — ${metadata.productName}`,
      '',
      `| 항목 | 값 |`,
      `|------|------|`,
      `| 검사 시작 | ${metadata.executionTime.start} |`,
      `| 검사 종료 | ${metadata.executionTime.end} |`,
      `| 소요 시간 | ${(metadata.executionTime.durationMs / 1000).toFixed(1)}s |`,
      `| 정책 | ${metadata.scanConfig.policies.join(', ')} |`,
      `| ACE 버전 | ${metadata.environment.aceVersion} |`,
      `| Extension 버전 | ${metadata.environment.extensionVersion} |`,
    ].join('\n');
  }

  private summarySection(report: FullReport): string {
    const { summary } = report;
    return [
      `## 📊 Summary`,
      '',
      `| 지표 | 수량 |`,
      `|------|------|`,
      `| 스캔 화면 수 | ${summary.totalScreens} |`,
      `| Violation | ${summary.totalIssues.violation} |`,
      `| Potential Violation | ${summary.totalIssues.potentialviolation} |`,
      `| Recommendation | ${summary.totalIssues.recommendation} |`,
      `| Manual Review | ${summary.totalIssues.manual} |`,
      `| Waiver 제외 | ${summary.filteredCount} |`,
      `| Flagged | ${summary.flaggedCount} |`,
    ].join('\n');
  }

  private topViolationsSection(report: FullReport): string {
    if (report.summary.topViolations.length === 0) {
      return '## 🏆 Top Violations\n\nNo violations found.';
    }

    const rows = report.summary.topViolations.map(
      (v, i) => `| ${i + 1} | \`${v.ruleId}\` | ${v.count} | ${v.message.substring(0, 80)} |`
    );

    return [
      `## 🏆 Top Violations`,
      '',
      `| # | Rule ID | Count | Message |`,
      `|---|---------|-------|---------|`,
      ...rows,
    ].join('\n');
  }

  private screenSection(screen: ScreenResult): string {
    const activeIssues = screen.issues.filter(i => i.filterStatus === 'active');
    const flaggedIssues = screen.issues.filter(i => i.filterStatus === 'flagged');

    const lines = [
      `---`,
      `### 📱 ${screen.name}`,
      '',
      `- **Depth**: ${screen.depth}`,
      `- **URL**: ${screen.url}`,
      `- **Path**: ${screen.path.length > 0 ? screen.path.join(' → ') : '(root)'}`,
      `- **Timestamp**: ${screen.timestamp}`,
      `- **Issues**: ${activeIssues.length} active, ${flaggedIssues.length} flagged`,
    ];

    if (activeIssues.length > 0) {
      lines.push('', '#### Violations & Issues', '');
      lines.push('| Level | Rule | Message | Snippet |');
      lines.push('|-------|------|---------|---------|');
      for (const issue of activeIssues) {
        const snippet = issue.snippet.replace(/\|/g, '\\|').substring(0, 60);
        lines.push(
          `| ${this.levelBadge(issue.level)} | \`${issue.ruleId}\` | ${issue.message.substring(0, 80)} | \`${snippet}\` |`
        );
      }
    }

    if (flaggedIssues.length > 0) {
      lines.push('', '#### ⚠️ Flagged (Waiver Applied)', '');
      lines.push('| Rule | Waiver ID | Message |');
      lines.push('|------|-----------|---------|');
      for (const issue of flaggedIssues) {
        lines.push(
          `| \`${issue.ruleId}\` | ${issue.waiverRuleId || '-'} | ${issue.message.substring(0, 80)} |`
        );
      }
    }

    return lines.join('\n');
  }

  private footer(report: FullReport): string {
    return [
      `---`,
      `> Generated by **LG ThinQ A11y Checker** v${report.metadata.environment.extensionVersion}`,
      `> Engine: IBM Accessibility Checker Engine (ACE) v${report.metadata.environment.aceVersion}`,
      `> License: Apache-2.0`,
    ].join('\n');
  }

  private levelBadge(level: string): string {
    const badges: Record<string, string> = {
      violation: '🔴 Violation',
      potentialviolation: '🟠 Potential',
      recommendation: '🔵 Recommend',
      potentialrecommendation: '🟣 Potential Rec',
      manual: '⚪ Manual',
    };
    return badges[level] || level;
  }
}
